[package]
name = "database"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]
members = [".", "entity", "migration"]

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }
