[package]
name = "database"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]
members = [".", "entity", "migration"]

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
migration = { path = "migration" }
