[package]
name = "entity"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
async-graphql = { version = "7.0.17", features = ["chrono"] }
serde = { version = "1.0.219", features = ["derive"] }

[dependencies.sea-orm]
version = "1.1.0"
