//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "flickr_photo_sizes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub flickr_photo_id: u64,
    pub server_id: String,
    pub secret: String,
    pub suffix: String,
    pub width: u32,
    pub height: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::flickr_photos::Entity",
        from = "Column::FlickrPhotoId",
        to = "super::flickr_photos::Column::FlickrId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    FlickrPhotos,
}

impl Related<super::flickr_photos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlickrPhotos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
