//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod directories;
pub mod flickr_photo_sizes;
pub mod flickr_photos;
pub mod flickr_photoset_tags;
pub mod flickr_photosets;
pub mod photo_files;
pub mod photo_reactions;
pub mod photo_tags;
pub mod photos;
pub mod sea_orm_active_enums;
pub mod tags;
pub mod users;
