//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use async_graphql::SimpleObject;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize, SimpleObject)]
#[sea_orm(table_name = "photo_files")]
pub struct Model {
    pub photo_id: u64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub directory_id: u64,
    pub name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub integrity: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directories::Entity",
        from = "Column::DirectoryId",
        to = "super::directories::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Directories,
    #[sea_orm(
        belongs_to = "super::photos::Entity",
        from = "Column::PhotoId",
        to = "super::photos::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Photos,
}

impl Related<super::directories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Directories.def()
    }
}

impl Related<super::photos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Photos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
