//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use async_graphql::Enum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Enum,
    Copy,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    DeriveIden,
    Deserialize,
    Serialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "tag_type")]
pub enum TagType {
    #[sea_orm(string_value = "category")]
    Category,
    #[sea_orm(string_value = "photographer")]
    Photographer,
}
