//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use async_graphql::SimpleObject;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize, SimpleObject)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub keycloak_sub: String,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::flickr_photosets::Entity")]
    FlickrPhotosets,
    #[sea_orm(has_many = "super::photo_reactions::Entity")]
    PhotoReactions,
}

impl Related<super::flickr_photosets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlickrPhotosets.def()
    }
}

impl Related<super::photo_reactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhotoReactions.def()
    }
}

impl Related<super::photos::Entity> for Entity {
    fn to() -> RelationDef {
        super::photo_reactions::Relation::Photos.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::photo_reactions::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
